name: Artilerija
version: '${project.version}'
main: youat0m.artilerija.Artilerija
api-version: 1.18
authors: [ YouAt0m ]
commands:
  shoot:
    usage: /shoot
  summonArt:
    usage: /summot art <максимальный заряд> <разброс)
  createProjectile:
    usage: /createammo <Weight> <Power>
  reloadGun:
    usage: /reloadGun [point]
  pointGun:
    usage: /point [pitch] [yaw]
