name: Artilerija
version: '${project.version}'
main: youat0m.artilerija.Artilerija
api-version: 1.18
authors: [ YouAt0m ]
commands:
  shoot:
    usage: /shoot
  summonArt:
    usage: /summot art
  createammo:
    usage: /createammo <Weight> <Power>